try...
ClassA.close()...
catch...
finally...
java.lang.RuntimeException: RuntimeException catch...
	at pkgs.pkgExes.Exe001.mtd(Exe001.java:26)
	at pkgs.pkgExes.Exe001.main(Exe001.java:13)
Caused by: java.lang.RuntimeException: RuntimeException try...
	at pkgs.pkgExes.Exe001.mtd(Exe001.java:23)
	... 1 more
	Suppressed: java.lang.RuntimeException: RuntimeException close()...
		at pkgs.pkgExes.ClassA.close(Exe001.java:5)
		at pkgs.pkgExes.Exe001.mtd(Exe001.java:24)
		... 1 more
